apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: example-gateway
  namespace: default
spec:
  gatewayClassName: kgateway
  listeners:
  - name: https
    protocol: HTTPS
    port: 443
    tls:
      mode: Terminate
      certificateRefs:
        - name: https
          kind: Secret
      options:
        kgateway.dev/signature-algorithm: "sha256,rsa:2048"
  - name: http
    protocol: HTTP
    port: 80
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: example-route
  namespace: default
spec:
  parentRefs:
    - name: example-gateway
  hostnames:
    - "example.com"
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /
      backendRefs:
      - name: httpbin
        port: 8000
---
kind: Secret
apiVersion: v1
metadata:
  name: https
  namespace: default
type: kubernetes.io/tls
data:
  tls.crt: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUNsekNDQVgrZ0F3SUJBZ0lCQVRBTkJna3Foa2lHOXcwQkFRc0ZBREFQTVEwd0N3WURWUVFEREFSMFpYTjAKTUI0WERUSTJNRGN6TURFMk5EazBOMW9YRFRJM01EY3pNREUyTkRrME4xb3dEekVOTUFzR0ExVUVBd3dFZEdWegpkRENDQVNJd0RRWUpLb1pJaHZjTkFRRUJCUUFEZ2dFUEFEQ0NBUW9DZ2dFQkFOcDFKMFV6NVhVcW0zT0FOdktoCithaDlxLzQ3dVJhTGMrVXB3MTlhSUNGOC9lZzNBby8zeEhhMG0vdVhReXdWTHNJWVZscmpKYzl2SHZZamxBVG4KTm1lTWlWblJqYzcwYnVxMzF1K0F4bit0RmdZZUpBM2lKVFdQY21MeDRhMk5IWWkyamFPYmpiUk03dk93SFJaNAowQ0lBT1V3Q3VIK3hnQ2JSSCs0RlpJd2tqK2pRemdSM0lnNnkvbngvUnFPT3BDK0ppRkNpYUFtNXlUQnNZbjc1CmlpbmVTY2Y4K2VEN1Z6YzJ3aTl4cFdSQTlMeWZYZ3I4c1FUbU1GYjR0RHhXOXBadXluemxheGZGak1aQ2MwNlgKODBlbGFjTkFSMVpuNW5kVXY2RWlSaERMNE9EQy95VG5RcWcvM2o4dzk5K2RVSkhBRDdXQm1JNFZWWDVaU1JlawpreUVDQXdFQUFUQU5CZ2txaGtpRzl3MEJBUXNGQUFPQ0FRRUFtaHZDWlQvMGtvZ2xkL2hXVEIzZCt1U2pnNnhICkRLczFUaTYzRlhSVitYaXpjWXZWQXhCcERRZEl4a0Z5NnFHYk5OZldpUG1EazJ4dDVhS2JOa1BRVmpBbmZUSlIKUFpMcHhyQnpUWlRUczV2cXVldC81dGNmaktmU3VYbVlEZXNZOG9BVGQwV1ZoQzJ3bFdmOUVYMkZLQjJpcVg4LwpFSFJHRFMyNDJrVlh2T1JpV0lqZmJtTGdkQVk3QzZmUHpZSjV1dDJOM1lkWndHWGVZN1AwMFBZbzJOUk5xU21SClp4MTd2ay9pTmJmTERFMnN5dDh2TkduNG4va0o5Qzl3eFltK2REN2VCTVJCM3VCUmh3MWtCTERGZGxRNWxnUTcKSmFBWTBmZXBuenhkc2ZzSHc5bmgrUWdBeE5GL2dvVFJLc2tLM1kwMTlFNEl3NEdlQzJIKzdjdWk5QT09Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
  tls.key: LS0tLS1CRUdJTiBSU0EgUFJJVkFURSBLRVktLS0tLQpNSUlFb3dJQkFBS0NBUUVBMm5VblJUUGxkU3FiYzRBMjhxSDVxSDJyL2p1NUZvdHo1U25EWDFvZ0lYejk2RGNDCmovZkVkclNiKzVkRExCVXV3aGhXV3VNbHoyOGU5aU9VQk9jMlo0eUpXZEdOenZSdTZyZlc3NERHZjYwV0JoNGsKRGVJbE5ZOXlZdkhoclkwZGlMYU5vNXVOdEV6dTg3QWRGbmpRSWdBNVRBSzRmN0dBSnRFZjdnVmtqQ1NQNk5ETwpCSGNpRHJMK2ZIOUdvNDZrTDRtSVVLSm9DYm5KTUd4aWZ2bUtLZDVKeC96NTRQdFhOemJDTDNHbFpFRDB2SjllCkN2eXhCT1l3VnZpMFBGYjJsbTdLZk9WckY4V014a0p6VHBmelI2VnB3MEJIVm1mbWQxUy9vU0pHRU12ZzRNTC8KSk9kQ3FEL2VQekQzMzUxUWtjQVB0WUdZamhWVmZsbEpGNlNUSVFJREFRQUJBb0lCQUM5cGNMSHd2dktNWWp1UgpqcHRmTXc5eDR2T2s0NWswZjkwekVLOXZvSHlVSTRrVDgwN3FuNjJCcWo3U3grWFgzUk9MODZYN0dYZ3BMa2VPClZqQXdQQnNDSWNjb0YwWmN2M3ZhbFYvYWkzb25SeG5oemNKam05N0JlTHBuczZxV2Ixdjkvc1NNM0piT2dhZksKeDYxYVlCV1pCZFpzMnJ6LytZZXpLR0pnc2o5Rnd6TGZLdFdmaE1seStBUG1aaUh4a0w1bklaOVZEbDVxTEJUcQoxQmtTOVQwRUVTWVZHaTZSQzFMVmkzdTIvY2JHRnZkaUxVYnEzMy9QTGhKaEdGMEduWkZkRE9yZVVtRHZUTVBFCkdmMFJVZHdsWHd0Wkd4dm5nbEdvMi9ra2hJbUZ0cmlEQzJsUnpJdmFGdUNDaFZVOExKdXRnZzdQcEtlTzJNVEIKcEs1RCtla0NnWUVBL3Z4YTJLWGdLZU51RUJGYnpRRFdsWUQ0RG9uby96RWNFU0ppSm1xdHo2L2lpRHJleTdXNQpnRlFaV1U0VlM4dlZhQjlVOU8xZForZjJrU3FFVisraE05aFpwVEZKNVhMM1I2NktYenNaaE01SEJxY2VOdGlCCkRVQ0pMZno5UVJjNDhFN1lPZElJRXJKVFRncjdGYmRZMHRVMWFTN0FJM1loTzc0elVRdTltVDBDZ1lFQTIxT2EKV1BWVUxkVHZkM1huTlB2T3NpbHJJVEtvUjgwNDdaYmtiY1pLTVdSc3c5TktBR3hNblFpWEFwS2xNSWxMZldXegpPS2RERzc2czNpOVhHOXF3ek92RTlUU0M0d1lWY3kwanVPQVRjUU15TnplR0hrS29iMkZwZ3VhRjFxZkVUZzc3CnFlV0piN3cxdHE3RnRob0ZqYnNRU3hJait5Mks1T2ZNNHhiSjE3VUNnWUFTek1obDhOVDJRYTU3d012ajhZdmcKdWdHUUVOcjg5Y0g4QVd6N0tDSm9qYTlHSEJFUk0vVFpZVm45RzZTMlVmRUtIRVZIU2JqNVVFRDlzd1RPOXZ3TAp0b2ZsaGh6TXJnMU5XN0VZRkdOdFIwZzFWVjBFN2pHVnFJeDB0NUowbWlHNGxoZWJLOEVzbjdsRXA4cWJiMGs5ClFqc041a1NFV05GYWRrdVNUaXRNZ1FLQmdEVDd4VldvTG1YRUF2V0E3aEhHb3ZBM1FVSUwwc3RGc0hMMCtNbnMKRlJCSmlsemtOZ1JVSlUzcVBWREp6RTRsWEs4MldrMWRXc0RoRnpHMWpmMlVueEZpQTNxWTdPV2JHcU53VENqbApPTTBjVUkwMlJKZ2Ewa1hWNm45TTRSZ3gveUk4VEYrR3ErVHFPcStmR1BRYzVTcVAvaWVrZ2p5emk5SXdqVFp1CjB1UGhBb0dCQUw5VVpJa1lHYjZldXBMOXZiWVdjcW41b3FsQjdyWDdPSDZuTUdweUVqaFNxSmtnTW9PelhjUWIKTG9vN2QxR044Vi9DWkpXcnVWQjlHckkzdEsvYVlZTS9ML21oS094ZkJnMy90czVhWnNNcmNQUTJZMmJrOGJhLwozcUhQQnNYM0FKb2R0ektSa0RRcjlqTlVBbWRpcWc4TkU5cTRkWnVTelVpWUNTcjJiWktzCi0tLS0tRU5EIFJTQSBQUklWQVRFIEtFWS0tLS0tCg==
